<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-23T22:28:55 IST" name="Suite" finished-at="2025-05-23T22:30:14 IST" duration-ms="78963">
    <groups>
    </groups>
    <test started-at="2025-05-23T22:28:55 IST" name="Validate Login Test" finished-at="2025-05-23T22:30:14 IST" duration-ms="78963">
      <class name="Automation.Tests.ValidateLoginTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:28:55 IST" name="launchApplication" finished-at="2025-05-23T22:29:55 IST" duration-ms="60439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="InvalidLogin()[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:29:55 IST" name="InvalidLogin" finished-at="2025-05-23T22:30:00 IST" duration-ms="5064" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Automation.Tests.ValidateLoginTest.InvalidLogin(ValidateLoginTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:30:00 IST" name="tearDown" finished-at="2025-05-23T22:30:01 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:30:01 IST" name="launchApplication" finished-at="2025-05-23T22:30:08 IST" duration-ms="7073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ValidLogin(java.util.HashMap)[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:30:08 IST" name="ValidLogin" data-provider="getData" finished-at="2025-05-23T22:30:13 IST" duration-ms="5626" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=secret_sauce, username=standard_user}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.interactions.Actions.sendKeys(java.lang.CharSequence[])" because "this.actions" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.interactions.Actions.sendKeys(java.lang.CharSequence[])" because "this.actions" is null
at Automation.Tests.ValidateLoginTest.ValidLogin(ValidateLoginTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Tests.ValidateLoginTest@5b408dc3]" started-at="2025-05-23T22:30:14 IST" name="tearDown" finished-at="2025-05-23T22:30:14 IST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Automation.Tests.ValidateLoginTest -->
    </test> <!-- Validate Login Test -->
  </suite> <!-- Suite -->
</testng-results>
